name: 编译 Flutter 为鸿蒙 APP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-harmony:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4.2.2

      - name: 安装 Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 安装鸿蒙适配版Flutter
        run: |
          git clone https://gitee.com/openharmony-sig/flutter_flutter.git
          echo "$GITHUB_WORKSPACE/flutter_flutter/bin" >> $GITHUB_PATH

      - name: 启用鸿蒙支持
        run: flutter config --enable-ohos

      - name: 生成鸿蒙目录
        run: flutter create --platforms=ohos .

      - name: 获取依赖
        run: flutter pub get

      - name: 编译鸿蒙HAP安装包
        run: flutter build hap --release

      - name: 上传编译好的鸿蒙APP
        uses: actions/upload-artifact@v4.4.3
        with:
          name: inkita-harmony-app
          path: ohos/build/outputs/default/*.hap
